<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateAreasTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('areas', function (Blueprint $table) {
            $table->increments('id');
            $table->string('post_office')->nullable();
            $table->string('name');
            $table->string('state_id');
            $table->timestamps();
        });

        DB::table('areas')->insert([
            ['name' => 'Bandar Maharani', 'state_id' => 1],
            ['name' => 'Bandar Penggaram', 'state_id' => 1],
            ['name' => 'Bukit Bakri', 'state_id' => 1],
            ['name' => 'Buloh Kasap', 'state_id' => 1],
            ['name' => 'Chaah', 'state_id' => 1],
            ['name' => 'Johor Bahru', 'state_id' => 1],
            ['name' => 'Kelapa Sawit', 'state_id' => 1],
            ['name' => 'Kluang', 'state_id' => 1],
            ['name' => 'Kota Tinggi', 'state_id' => 1],
            ['name' => 'Kulai', 'state_id' => 1],
            ['name' => 'Labis', 'state_id' => 1],
            ['name' => 'Ledang', 'state_id' => 1],
            ['name' => 'Masai', 'state_id' => 1],
            ['name' => 'Mersing', 'state_id' => 1],
            ['name' => 'Parit Raja', 'state_id' => 1],
            ['name' => 'Pasir Gudang', 'state_id' => 1],
            ['name' => 'Pekan Nenas', 'state_id' => 1],
            ['name' => 'Pontian Kecil', 'state_id' => 1],
            ['name' => 'Segamat', 'state_id' => 1],
            ['name' => 'Sekudai', 'state_id' => 1],
            ['name' => 'Senai', 'state_id' => 1],
            ['name' => 'Simpang Rengam', 'state_id' => 1],
            ['name' => 'Tangkak', 'state_id' => 1],
            ['name' => 'Ulu Tiram', 'state_id' => 1],
            ['name' => 'Yong Peng', 'state_id' => 1],
            ['name' => 'Alor Setar', 'state_id' => 2],
            ['name' => 'Bailing', 'state_id' => 2],
            ['name' => 'Bedong', 'state_id' => 2],
            ['name' => 'Gurun', 'state_id' => 2],
            ['name' => 'Jitra', 'state_id' => 2],
            ['name' => 'Kuah', 'state_id' => 2],
            ['name' => 'Kuala Kedah', 'state_id' => 2],
            ['name' => 'Kulim', 'state_id' => 2],
            ['name' => 'Langgar', 'state_id' => 2],
            ['name' => 'Sungai Petani', 'state_id' => 2],
            ['name' => 'Gua Musang', 'state_id' => 3],
            ['name' => 'Kadok', 'state_id' => 3],
            ['name' => 'Kota Bahru', 'state_id' => 3],
            ['name' => 'Kuala Krai', 'state_id' => 3],
            ['name' => 'Pangkal Kalong', 'state_id' => 3],
            ['name' => 'Pasir Mas', 'state_id' => 3],
            ['name' => 'Peringat', 'state_id' => 3],
            ['name' => 'Tanah Merah', 'state_id' => 3],
            ['name' => 'Tumpat', 'state_id' => 3],
            ['name' => 'Wakaf Baru', 'state_id' => 3],
            ['name' => 'Bukit Bintang', 'state_id' => 4],
            ['name' => 'Titiwangsa', 'state_id' => 4],
            ['name' => 'Setiawangsa', 'state_id' => 4],
            ['name' => 'Wangsa Maju', 'state_id' => 4],
            ['name' => 'Kepong', 'state_id' => 4],
            ['name' => 'Segambut', 'state_id' => 4],
            ['name' => 'Lembah Pantai', 'state_id' => 4],
            ['name' => 'Seputeh', 'state_id' => 4],
            ['name' => 'Bandar Tun Razak', 'state_id' => 4],
            ['name' => 'Cheras', 'state_id' => 4],
            ['name' => 'Labuan', 'state_id' => 5],
            ['name' => 'Alor Gajah', 'state_id' => 6],
            ['name' => 'Ayer Keroh', 'state_id' => 6],
            ['name' => 'Ayer Molek', 'state_id' => 6],
            ['name' => 'Batu Berendam', 'state_id' => 6],
            ['name' => 'Bemban', 'state_id' => 6],
            ['name' => 'Bukit Baru', 'state_id' => 6],
            ['name' => 'Bukit Rambai', 'state_id' => 6],
            ['name' => 'Klebang', 'state_id' => 6],
            ['name' => 'Kuala Sungai Baru', 'state_id' => 6],
            ['name' => 'Masjid Tanah', 'state_id' => 6],
            ['name' => 'Melaka', 'state_id' => 6],
            ['name' => 'Pulau Sebang', 'state_id' => 6],
            ['name' => 'Sungai Udang', 'state_id' => 6],
            ['name' => 'Seremban', 'state_id' => 7],
            ['name' => 'Jempol', 'state_id' => 7],
            ['name' => 'Port Dickson', 'state_id' => 7],
            ['name' => 'Tampin', 'state_id' => 7],
            ['name' => 'Kuala Pilah', 'state_id' => 7],
            ['name' => 'Rembau', 'state_id' => 7],
            ['name' => 'Jelebu', 'state_id' => 7],
            ['name' => 'Bandar Jengka Pusat', 'state_id' => 8],
            ['name' => 'Bentong', 'state_id' => 8],
            ['name' => 'Bukit Tinggi', 'state_id' => 8],
            ['name' => 'Jerantut', 'state_id' => 8],
            ['name' => 'Karak', 'state_id' => 8],
            ['name' => 'Kuala Lipis', 'state_id' => 8],
            ['name' => 'Kuantan', 'state_id' => 8],
            ['name' => 'Mentakab', 'state_id' => 8],
            ['name' => 'Pekan', 'state_id' => 8],
            ['name' => 'Raub', 'state_id' => 8],
            ['name' => 'Temerloh', 'state_id' => 8],
            ['name' => 'Bayan Lepas', 'state_id' => 9],
            ['name' => 'Church Town', 'state_id' => 9],
            ['name' => 'George Town', 'state_id' => 9],
            ['name' => 'Ayer Tawar', 'state_id' => 10],
            ['name' => 'Bagan Serai', 'state_id' => 10],
            ['name' => 'Batu Gajah', 'state_id' => 10],
            ['name' => 'Bidor', 'state_id' => 10],
            ['name' => 'Ipoh', 'state_id' => 10],
            ['name' => 'Jelapang', 'state_id' => 10],
            ['name' => 'Kampar', 'state_id' => 10],
            ['name' => 'Kampong Koh', 'state_id' => 10],
            ['name' => 'Kuala Kangsar', 'state_id' => 10],
            ['name' => 'Lawan Kuda Baharu', 'state_id' => 10],
            ['name' => 'Lumut', 'state_id' => 10],
            ['name' => 'Pantai Remis', 'state_id' => 10],
            ['name' => 'Parit Buntar', 'state_id' => 10],
            ['name' => 'Perak', 'state_id' => 10],
            ['name' => 'Pusing', 'state_id' => 10],
            ['name' => 'Simpang Empat', 'state_id' => 10],
            ['name' => 'Sungai Siput Utara', 'state_id' => 10],
            ['name' => 'Taiping', 'state_id' => 10],
            ['name' => 'Tanjong Malim', 'state_id' => 10],
            ['name' => 'Tapah', 'state_id' => 10],
            ['name' => 'Teluk Intan', 'state_id' => 10],
            ['name' => 'Kangar', 'state_id' => 11],
            ['name' => 'Kuala Perlis', 'state_id' => 12],
            ['name' => 'Beaufort', 'state_id' => 13],
            ['name' => 'Donggongon', 'state_id' => 13],
            ['name' => 'Keningau', 'state_id' => 13],
            ['name' => 'Kinarut', 'state_id' => 13],
            ['name' => 'Kota Belud', 'state_id' => 13],
            ['name' => 'Kota Kinabalu', 'state_id' => 13],
            ['name' => 'Kudat', 'state_id' => 13],
            ['name' => 'Kunak', 'state_id' => 13],
            ['name' => 'Lahad Datu', 'state_id' => 13],
            ['name' => 'Papar', 'state_id' => 13],
            ['name' => 'Putatan', 'state_id' => 13],
            ['name' => 'Ranau', 'state_id' => 13],
            ['name' => 'Sandakan', 'state_id' => 13],
            ['name' => 'Semporna', 'state_id' => 13],
            ['name' => 'Tawau', 'state_id' => 13],
            ['name' => 'Batu Delapan Bazaar', 'state_id' => 15],
            ['name' => 'Bintulu', 'state_id' => 15],
            ['name' => 'Kapit', 'state_id' => 15],
            ['name' => 'Kota Samarahan', 'state_id' => 15],
            ['name' => 'Kuching', 'state_id' => 15],
            ['name' => 'Limbang', 'state_id' => 15],
            ['name' => 'Miri', 'state_id' => 15],
            ['name' => 'Sarikel', 'state_id' => 15],
            ['name' => 'Sibu', 'state_id' => 15],
            ['name' => 'Sri Aman', 'state_id' => 15],
            ['name' => 'Ampang', 'state_id' => 15],
            ['name' => 'Ampang Jaya', 'state_id' => 15],
            ['name' => 'Balakong', 'state_id' => 15],
            ['name' => 'Bandar Baru Bangi', 'state_id' => 15],
            ['name' => 'Bandar Baru Salak Tinggi', 'state_id' => 15],
            ['name' => 'Bander Baro Bangi', 'state_id' => 15],
            ['name' => 'Banting', 'state_id' => 15],
            ['name' => 'Batang Berjuntai', 'state_id' => 15],
            ['name' => 'Batu Arang', 'state_id' => 15],
            ['name' => 'Batu Sembilan Cheras', 'state_id' => 15],
            ['name' => 'Beranang', 'state_id' => 15],
            ['name' => 'Bukit Beruntung', 'state_id' => 15],
            ['name' => 'Cyberjaya', 'state_id' => 15],
            ['name' => 'Darul Ehsan', 'state_id' => 15],
            ['name' => 'Dungun', 'state_id' => 15],
            ['name' => 'Gombak Setia', 'state_id' => 15],
            ['name' => 'Jenjarom', 'state_id' => 15],
            ['name' => 'Kajang', 'state_id' => 15],
            ['name' => 'Kajang-Sungai Chua', 'state_id' => 15],
            ['name' => 'Klang', 'state_id' => 15],
            ['name' => 'Kuala Kubu Baru', 'state_id' => 15],
            ['name' => 'Kuala Selangor', 'state_id' => 15],
            ['name' => 'Kuang', 'state_id' => 15],
            ['name' => 'Pengkalan Kundang', 'state_id' => 15],
            ['name' => 'Petaling Jaya', 'state_id' => 15],
            ['name' => 'Port Klang', 'state_id' => 15],
            ['name' => 'Puchong', 'state_id' => 15],
            ['name' => 'Rawang', 'state_id' => 15],
            ['name' => 'Sabak', 'state_id' => 15],
            ['name' => 'Sekinchan', 'state_id' => 15],
            ['name' => 'Selayang Baru', 'state_id' => 15],
            ['name' => 'Semenyih', 'state_id' => 15],
            ['name' => 'Serendah', 'state_id' => 15],
            ['name' => 'Seri Kembangan', 'state_id' => 15],
            ['name' => 'Shah Alam', 'state_id' => 15],
            ['name' => 'Subang Jaya', 'state_id' => 15],
            ['name' => 'Sungai Besar', 'state_id' => 15],
            ['name' => 'Sungai Buloh', 'state_id' => 15],
            ['name' => 'Sungai Pelek', 'state_id' => 15],
            ['name' => 'Taman Greenwood', 'state_id' => 15],
            ['name' => 'Tanjong Karang', 'state_id' => 15],
            ['name' => 'Tanjong Sepat', 'state_id' => 15],
            ['name' => 'Langkap', 'state_id' => 10],
            ['name' => 'Cukai', 'state_id' => 16],
            ['name' => 'Jertih', 'state_id' => 16],
            ['name' => 'Kemaman', 'state_id' => 16],
            ['name' => 'Kerteh', 'state_id' => 16],
            ['name' => 'Kuala Terengganu', 'state_id' => 16],
            ['name' => 'Marang', 'state_id' => 16],
            ['name' => 'Paka', 'state_id' => 16],
            ['name' => 'Serdang', 'state_id' => 16],
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('areas');
    }
}
